# Generated by Django 4.2 on 2025-05-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_exceptional', models.CharField(max_length=155)),
                ('description_exceptional', models.TextField()),
                ('title_profesional', models.CharField(max_length=155)),
                ('description_profesional', models.TextField()),
                ('title_services', models.CharField(max_length=155)),
                ('description_services', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Настройки Страницы Услуги',
            },
        ),
    ]
