# Generated by Django 4.2 on 2025-05-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='services')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
