# Generated by Django 4.2 on 2025-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespagesettings',
            name='image',
            field=models.ImageField(default=1, upload_to='services'),
            preserve_default=False,
        ),
    ]
