# Generated by Django 4.2 on 2025-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('year', models.CharField(max_length=155)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='about_page')),
                ('title_choices_us', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('title_ceo', models.CharField(max_length=155)),
                ('description_ceo', models.TextField()),
                ('image_ceo', models.ImageField(upload_to='about_page')),
            ],
            options={
                'verbose_name_plural': 'Настройки Страницы О нас',
            },
        ),
    ]
