# Generated by Django 4.2 on 2025-05-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesettings',
            name='name_ceo',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
