# Generated by Django 4.2 on 2025-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpagesettings_name_ceo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='advantages')),
            ],
            options={
                'verbose_name_plural': 'Наши Примущество',
            },
        ),
    ]
