# Generated by Django 4.2 on 2025-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebanner',
            name='button_link',
            field=models.URLField(default='/contact.html'),
        ),
        migrations.AddField(
            model_name='basebanner',
            name='button_text',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
    ]
