# Generated by Django 4.2 on 2025-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_basebanner_button_link_basebanner_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=155)),
                ('title_athor', models.CharField(max_length=155)),
                ('title_manager', models.CharField(max_length=155)),
                ('manager', models.CharField(max_length=155)),
                ('description_about', models.TextField()),
                ('title_services', models.CharField(max_length=155)),
                ('description_service', models.TextField()),
                ('title_cases', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('title_static', models.CharField(max_length=155)),
                ('description_static', models.TextField()),
                ('image_static', models.ImageField(upload_to='settings')),
                ('title_news', models.CharField(max_length=155)),
                ('description_news', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Главная Настройки',
            },
        ),
    ]
