# Generated by Django 4.2 on 2025-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_cases',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image_author',
            field=models.ImageField(default=1, upload_to='settings'),
            preserve_default=False,
        ),
    ]
