# Generated by Django 4.2 on 2025-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_description_cases_settings_image_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='image_static',
            new_name='image_static1',
        ),
        migrations.AddField(
            model_name='settings',
            name='image_static2',
            field=models.ImageField(default=1, upload_to='settings'),
            preserve_default=False,
        ),
    ]
