# Generated by Django 4.2 on 2025-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_image_static_settings_image_static1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_contact',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title_contact',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
