# Generated by Django 4.2 on 2025-05-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_description_contact_settings_title_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Financial Planning', 'Financial Planning'), ('Savings & Investments', 'Savings & Investments'), ('Private Banking', 'Private Banking'), ('Consumer Leasing', 'Consumer Leasing')], max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Наши услуги',
            },
        ),
    ]
