# Generated by Django 4.2 on 2025-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cases')),
            ],
            options={
                'verbose_name_plural': 'Случай',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('percent', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Наши статистики',
            },
        ),
    ]
