# Generated by Django 4.2 on 2025-05-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_cases_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news')),
                ('data', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Наши новости',
            },
        ),
    ]
