# Generated by Django 4.2 on 2025-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('type_info', models.CharField(max_length=155)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Форма Обратной связи',
            },
        ),
    ]
